project:
  type: website

website:
  title: "Flowrate and outlet pressure"
  navbar:
    left:
      - href: index.qmd
        text: No wells

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
