project:
  type: website

website:
  title: Flowrate and outlet pressure
  body-footer: "[GitHub](https://github.com/Jerell/dtdiag)"
  repo-url: https://github.com/Jerell/dtdiag
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: No wells

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
