---
title: "No wells"
format:
  html:
    code-fold: true
---

## Flowrate/Pressure peaks

After excluding rows that entered the two phase region, there are two cases where the greatest outlet pressure for an inlet pressure was not at a flowrate of 1 kgps. 

```{python}
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

df = pd.read_csv("./dt/solver-out-2023-04-13_151111322_(temp=10C, inc=1).txt")
df = df.loc[df["FluidPressureAtReservoirBara"] > 0.01]
noTwoPhase = df.loc[df["WasTwoPhase"] == False]

grouped = noTwoPhase.groupby("InletPressureBara")
maxFR = noTwoPhase.loc[
    noTwoPhase.groupby("InletPressureBara")["FluidPressureAtReservoirBara"].idxmax()
]
maxFR.loc[maxFR["InletFlowrateKgps"] > 1]
```

```{python}

colors = {False: "tab:blue", True: "tab:orange"}


def draw_plot(df_plot, pressureBara, temperatureCelsius):
    df_plot = df_plot.dropna()
    df_plot = df_plot[(df_plot["InletPressureBara"] == pressureBara)]
    fig = plt.figure()
    ax = fig.add_subplot()
    ax.scatter(
        df_plot["InletFlowrateKgps"],
        df_plot["FluidPressureAtReservoirBara"],
        c=df_plot["WasTwoPhase"].map(colors),
    )
    ax.set_xlabel("Inlet flowrate")
    ax.set_ylabel("Outlet pressure")

    handles = [
        Line2D(
            [0], [0], marker="o", color="w", markerfacecolor=v, label=k, markersize=8
        )
        for k, v in colors.items()
    ]
    ax.legend(
        title="WasTwoPhase", handles=handles, bbox_to_anchor=(1.05, 1), loc="upper left"
    )
    plt.grid()
    plt.show()


```

```{python}
# | label: fig-nw69bara
# | fig-cap: No well - 69 Bara, 10°C

draw_plot(df, 69, 10)
```

```{python}
# | label: fig-nw77bara
# | fig-cap: No well - 77 Bara, 10°C

draw_plot(df, 77, 10)
```

## Two phase and discontinuities

There is often, but not always, an outlet pressure discontinuity in cases that have entered the two phase region at or before the final pipe segment.


In @fig-nw80bara, the discontinuity is early in the set of cases that entered two phase.

```{python}
# | label: fig-nw80bara
# | fig-cap: No well - 80 Bara, 10°C

draw_plot(df, 80, 10)
```

Despite entering two phase, there was no discontinuity in @fig-nw45bara. It doesn't seem to be the case that *just* entering the two phase region will cause a discontinuity. It could be related to where it happens, from which direction, or what pressure it happens at.

```{python}
# | label: fig-nw45bara
# | fig-cap: No well - 45 Bara, 10°C

draw_plot(df, 45, 10)
```

```{python}
# | label: fig-nw40bara
# | fig-cap: No well - 40 Bara, 10°C

draw_plot(df, 40, 10)
```

```{python}
# | label: fig-nw72bara
# | fig-cap: No well - 72 Bara, 10°C

draw_plot(df, 72, 10)
```

```{python}
# | label: fig-nw71bara
# | fig-cap: No well - 71 Bara, 10°C

draw_plot(df, 71, 10)
```

```{python}
# | label: fig-nw70bara
# | fig-cap: No well - 70 Bara, 10°C

draw_plot(df, 70, 10)
```

# [Data](dt/solver-out-2023-04-13_151111322_(temp=10C, inc=1).txt)

```{python}
df
```